### ISSUE TITLE
have json be in current dirrectory

### ISSUE THREAD

**Issue by calvinmetcalf** [tmcw/ownership#2]
idea: instead of having the packages.json and the owners.json be based on the tool, just have it look for them in the current directory

**Comment by tmcw** [comment]
Right now the main point of them being in the tool is that upgrading the tool === upgrading the list, which makes it clear which version you're using and easy to tell people what to do - just run `npm install -g *-owners` again.

**Comment by tmcw** [comment]
👍 Happy to accept a PR implementing this change! For the Mapbox usecase, we're planning to switch to organizations, so it's not on my list to implement.
